use DataWareHouse;

SELECT DISTINCT country from gold.dim_customers;



-- Retrieve a list of unique categories, subcategories, and products

SELECT DISTINCT product_name,category,subcategory from gold.dim_products;

-- Determine the first and last order date and the total duration in months

SELECT min(order_date) as first_order,
max(order_date) as last_order,
DATEDIFF(MONTH,min(order_date),max(order_date)) as order_range_in_months
from gold.fact_sales;



-- Find the youngest and oldest customer based on birthdate


SELECT min(birthdate) as oldest_customer,
DATEDIFF(year,min(birthdate),getDate()) as oldest_customer_age,
max(birthdate) as youngest_customer,
DATEDIFF(year,max(birthdate),getDate()) as youngest_customer_age
from gold.dim_customers;





-- Find the Total Sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales

-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales

-- Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales

-- Find the Total number of Orders
SELECT COUNT(order_number) AS total_orders FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales

-- Find the total number of products
SELECT COUNT(product_name) AS total_products FROM gold.dim_products

-- Find the total number of customers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers;

-- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.fact_sales;



SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Products', COUNT(DISTINCT product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total Customers', COUNT(customer_key) FROM gold.dim_customers;






-- Find total customers by countries


SELECT 
country,
count(customer_key) as total_customers
from 
gold.dim_customers
group by country

-- total customers by gender


SELECT gender,
count(customer_key) as total_customers
from gold.dim_customers
group by gender
Order by total_customers DESC;


-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;



-- What is the average costs in each category?


SELECT category,
avg(cost) as avg_cost
from gold.dim_products
group by category;




-- What is the total revenue generated for each category?


SELECT
p.CATEGORY,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f 
left join gold.dim_products p
on p.product_key = f.product_key
group by p.CATEGORY



-- What is the total revenue generated by each customer?


SELECT 
c.first_name,
sum(sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key = c.customer_key
group by c.first_name



-- Which 5 products Generating the Highest Revenue?
-- Simple Ranking

SELECT top 5
p.product_name,
sum(f.sales_amount) as total_sales
from gold.fact_sales f 
left join gold.dim_products p
on p.product_key = f.product_key
group by p.product_name
ORDER BY total_sales DESC



-- Which 5 products Generating the lowest Revenue?



SELECT top 5
p.product_name,
sum(f.sales_amount) as total_sales
from gold.fact_sales f 
left join gold.dim_products p
on p.product_key = f.product_key
group by p.product_name
ORDER BY total_sales ASC


-- 

-- Find the top 10 customers who have generated the highest revenue

SELECT top 10
c.first_name,
sum(sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key = c.customer_key
group by c.first_name
order by total_revenue DESC
